#!/usr/bin/env python3
"""Convert constrained local visual-review answers into audited selections.

The reviewer may choose only an evidence_id generated by the review queue.  This keeps
manual review grounded in OCR coordinates: no value or bbox can be invented here.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--queue", type=Path, default=Path("artifacts/review_queue/queue.json"))
    parser.add_argument("--answers", type=Path, default=Path("artifacts/manual_review_answers.json"))
    parser.add_argument("--output", type=Path, default=Path("artifacts/manual_selections.json"))
    args = parser.parse_args()

    queue = {task["task_id"]: task for task in json.loads(args.queue.read_text())["tasks"]}
    answers = json.loads(args.answers.read_text()).get("answers", {})
    documents: dict[str, dict] = {}
    rejected: list[dict[str, str]] = []

    for task_id, answer in answers.items():
        if answer.get("status") != "resolved":
            continue
        task = queue.get(task_id)
        if task is None:
            rejected.append({"task_id": task_id, "reason": "task is no longer unresolved"})
            continue
        evidence_id = answer.get("evidence_id")
        evidence = next((item for item in task["evidence_values"] if item["evidence_id"] == evidence_id), None)
        if evidence is None:
            rejected.append({"task_id": task_id, "reason": "evidence_id is not in the current review queue"})
            continue
        document = documents.setdefault(
            task["document_id"],
            {
                "siren": task["siren"], "pdf": task["pdf"], "document_id": task["document_id"],
                "fiscal_year_end": task["fiscal_year_end"], "selections": [],
            },
        )
        document["selections"].append(
            {
                "field_key": task["field_key"], "value": evidence["parsed_value"], "page": evidence["page"],
                "bbox_px": evidence["bbox_px"], "label": evidence["label"],
                "column_header": evidence.get("column_header") or "manual visual selection",
                "fiscal_year_end": task["fiscal_year_end"], "confidence": 0.85,
                "selection_reason": f"local visual review: {evidence_id}; {answer.get('reason', '')}",
            }
        )

    payload = {"documents": list(documents.values()), "rejected_answers": rejected}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    accepted = sum(len(document["selections"]) for document in documents.values())
    print(f"Wrote {args.output} with {accepted} reviewed selections; rejected {len(rejected)} answers")


if __name__ == "__main__":
    main()
